version: '1'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder           # Para desarrollo con Vite
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5174:5174"
    command: npm run dev

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: final             # Ahora sí existe la etapa "final"
    ports:
      - "5173:80"

